copy-icon action build
copy-icon action delete
copy-icon action done
copy-icon action explore
copy-icon action find_in_page
copy-icon action help
copy-icon action info
copy-icon action lock
copy-icon action lock_open
copy-icon action pan_tool
copy-icon action search
copy-icon action settings
copy-icon action timeline
copy-icon action touch_app
copy-icon action zoom_in
copy-icon action zoom_out
copy-icon alert error
copy-icon alert warning
copy-icon communication call
copy-icon communication comment
copy-icon communication email
copy-icon content add
copy-icon content clear
copy-icon content content_cut
copy-icon content create
copy-icon content flag
copy-icon content redo
copy-icon content remove
copy-icon content undo
copy-icon device gps_fixed
copy-icon device gps_not_fixed
copy-icon device gps_off
copy-icon device location_searching
copy-icon editor show_chart
copy-icon file cloud_done
copy-icon file cloud_download
copy-icon image wb_sunny
copy-icon maps my_location
copy-icon maps navigation
copy-icon navigation arrow_back
copy-icon navigation check
copy-icon navigation close
copy-icon navigation menu
copy-icon navigation more_vert
copy-icon notification do_not_disturb
copy-icon notification sd_card
copy-icon notification wifi
copy-icon social person
copy-icon social person_outline
copy-icon toggle star
