#! /usr/bin/bash

####################################################################################################
#
# Script to generate all the schemas
#
####################################################################################################

####################################################################################################
#
# This file is part of the Alpine Toolkit software.
# Copyright (C) 2017 Fabrice Salvaire
# Contact: http://www.fabrice-salvaire.fr
# SPDX-License-Identifier: GPL-3.0-only
#
####################################################################################################

generate Schemas.Blog

generate Schemas.Bleau
generate Schemas.CampToCamp
generate Schemas.Document
generate Schemas.ThirdPartyLicense
generate Schemas.Refuge
generate Schemas.Settings
