#! /usr/bin/env python3
# -*- Python -*-

####################################################################################################
#
# $QTCARTO_BEGIN_LICENSE:GPL3$
#
# Copyright (C) 2016 Fabrice Salvaire
# Contact: http://www.fabrice-salvaire.fr
#
# This file is part of the QtCarto library.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# $QTCARTO_END_LICENSE$
#
####################################################################################################

####################################################################################################

import os
import json

from SqlOrm import SchemaRepository

from GeneratorSettings import generator_settings

####################################################################################################

source_path = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# print(source_path)

document_dir = os.path.join(source_path, 'src', 'document')

####################################################################################################

# "name": "ffcam-refuges.json",
# "author": "Fabrice Salvaire",
# "version": 1,
# "date": "2017-04-21T18:28:11Z",
# "description": "Base de données  des refuges FFCAM",
# "url": "filer_public/ef/c7/efc713f4-e797-458c-9844-9bc3ae8fe3eb/ffcam-refuges.json",
# "size": 74840

####################################################################################################

json_schema = {
    'document': {
        'name': { 'type':'text' },
        'author': { 'type':'text' },
        'version': { 'type':'integer' },
        'date': { 'type':'text', 'qt_type':'QDateTime' },
        'description': { 'type':'text' },
        'url': { 'type':'text', 'qt_type':'QUrl' },
        'size': { 'type':'integer' },
    }
}

json_data = json.dumps(json_schema, indent=4)
# print(json_data)

schema_repository = SchemaRepository(json_data)

for table in schema_repository:
    print('Table', table.name)
    print(table.to_sql())
    header, source = table.generate_source(table.name, generator_settings)
    print(header)
    print(source)
    with open(os.path.join(document_dir, 'document.h'), 'w') as f:
        f.write(str(header))
    with open(os.path.join(document_dir, 'document.cpp'), 'w') as f:
        f.write(str(source))
