#! /usr/bin/env python3
# -*- Python -*-

####################################################################################################
#
# $QTCARTO_BEGIN_LICENSE:GPL3$
#
# Copyright (C) 2016 Fabrice Salvaire
# Contact: http://www.fabrice-salvaire.fr
#
# This file is part of the QtCarto library.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# $QTCARTO_END_LICENSE$
#
####################################################################################################

####################################################################################################

import os
import sys

code_generator_path = os.path.dirname(os.path.abspath(__file__))
source_path = os.path.dirname(code_generator_path)
# print(source_path)

sys.path.insert(0, code_generator_path)

####################################################################################################

import json

from CodeGenerator.SqlOrm import (SchemaRepository,
                                  Schema,
                                  IntegerField, StringField, UrlField,
                                  DateTimeField, IsoDateTimeField, UnixDateTimeField)

from CodeGenerator.GeneratorSettings import generator_settings

####################################################################################################

# "name": "ffcam-refuges.json",
# "author": "Fabrice Salvaire",
# "version": 1,
# "date": "2017-04-21T18:28:11Z",
# "description": "Base de données  des refuges FFCAM",
# "url": "filer_public/ef/c7/efc713f4-e797-458c-9844-9bc3ae8fe3eb/ffcam-refuges.json",
# "size": 74840

####################################################################################################

class Document(Schema):

    __table_name__ = 'document'

    __order__ = (
        'id',
        'name',
        'author',
        'version',
        'date',
        'description',
        'url',
        'size',
    )

    id = IntegerField(primary_key=True)
    name= StringField()
    author= StringField()
    version = IntegerField()
    date = UnixDateTimeField()
    description= StringField()
    url = UrlField()
    size = IntegerField()

####################################################################################################

schema_repository = SchemaRepository('DocumentDatabaseSchema', Document)

output_dir = os.path.join(source_path, 'src', 'document')
path = os.path.join(output_dir, 'document')
schema_repository.write_source(path, generator_settings)
