#! /usr/bin/env python3
# -*- mode: python -*-

####################################################################################################

import importlib
import json
import os
import sys

####################################################################################################

generator_path = os.path.dirname(os.path.abspath(__file__))
# source_path = os.path.dirname(code_generator_path)

sys.path.insert(0, generator_path)

####################################################################################################

import InspectorTools as IT

####################################################################################################

json_root = {}

json_root['v6_version'] = {
    directory: IT.git_head_hex(os.path.join(generator_path, directory))
    for directory in ('v6_common', 'v6_api')}

####################################################################################################
#
# Definitions
#

# associations
import c2corg_common.associations
associations = {}
for parent, child in c2corg_common.associations.valid_associations:
    if parent not in associations:
        associations[parent] = []
    associations[parent].append(child)
json_root['associations'] = associations

# attributes
import c2corg_common.attributes
json_root['attributes'] = {
    obj_name:obj
    for obj_name, obj in IT.yield_list_in_module(c2corg_common.attributes)}

# document_types
import c2corg_common.document_types
json_root['document_types'] = {}
for obj_name, obj in IT.yield_string_in_module(c2corg_common.document_types):
    if obj_name.endswith('_TYPE'):
        obj_name = obj_name.lower().replace('_type', '')
        json_root['document_types'][obj_name] = obj
# print(sorted(json_root['document_types'].keys()))

json_root['document_fields'] = {}
for document_type in (
        'area',
        'article',
        'book',
        'image',
        'outing',
        'route',
        'topo_map',
        'user_profile',
        'waypoint',
        'xreport',
        ):
    submodule = 'fields_' + document_type
    module_name = 'c2corg_common.' + submodule
    module = importlib.import_module(module_name)
    fields = getattr(module, submodule)
    json_root['document_fields'][document_type] = fields

# sortable_search_attributes
import c2corg_common.sortable_search_attributes
json_root['sortable_search_attributes'] = {
    obj_name:obj
    for obj_name, obj in IT.yield_dict_in_module(c2corg_common.sortable_search_attributes)}

####################################################################################################

with open('camptocamp-definitions.json', 'w') as fd:
    json.dump(json_root, fd, indent=4, sort_keys=True)
