#! /bin/bash

category=$1
name=$2
dp="24"

mdi_path="$HOME/home/developpement/qtcarto-application/material-design-ressources/material-design-icons"

function copy_link() {
  colour=$1
  dpi=$2
  scale=$3

  subdir="${category}/drawable-${dpi}"
  src="ic_${name}_${colour}_${dp}dp.png"
  target=$(tr "_" "-" <<<"${name}-${colour}${scale}.png")
  mkdir -p ${subdir}
  cp ${mdi_path}/${subdir}/${src} ${subdir}
  rm -f ${target}
  ln -sf ${subdir}/${src} ${target}
}

for colour in white black ; do
  copy_link ${colour} mdpi
  copy_link ${colour} xhdpi @2x
  copy_link ${colour} xxhdpi @3x
  copy_link ${colour} xxxhdpi @4x
done

# end
