// -*- mode: c++ -*-
// This file was automatically generated by SqlOrm
/***************************************************************************************************
 *
 * $QTCARTO_BEGIN_LICENSE:GPL3$
 *
 * Copyright (C) 2016 Fabrice Salvaire
 * Contact: http://www.fabrice-salvaire.fr
 *
 * This file is part of the QtCarto library.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * $QTCARTO_END_LICENSE$
 *
 **************************************************************************************************/

/**************************************************************************************************/

#ifndef __BLOG_H__
#define __BLOG_H__

/**************************************************************************************************/

#include <QDataStream>
#include <QDateTime>
#include <QJsonObject>
#include <QSharedPointer>
#include <QSqlQuery>
#include <QSqlRecord>
#include <QString>
#include <QVariant>
#include <QVariantList>
#include <QtDebug>

#include "database/schema.h"
#include "database/database_schema.h"
#include "database/database_row.h"
#include "database/database_row_list.h"

/**************************************************************************************************/

class Author;

class AuthorSchema : public QcSchema
{
public:
  enum Fields {
    ID,
    NAME,
    BIRTHDATE
  };
  static const int NUMBER_OF_FIELDS = 3;

public:
  static AuthorSchema & instance()
  {
    static AuthorSchema m_instance;
    return m_instance;
  }

  // delete copy and move constructors and assign operators
  AuthorSchema(const AuthorSchema &) = delete;
  AuthorSchema(AuthorSchema &&) = delete;
  AuthorSchema & operator=(const AuthorSchema &) = delete;
  AuthorSchema & operator=(AuthorSchema &&) = delete;

protected:
  AuthorSchema();
  ~AuthorSchema();
};

/**************************************************************************************************/



class AuthorPtr;



class Blog;



class Author : public QObject, public QcRow<AuthorSchema>
{
  Q_OBJECT
  Q_PROPERTY(int id READ id WRITE set_id NOTIFY idChanged)
  Q_PROPERTY(QString name READ name WRITE set_name NOTIFY nameChanged)
  Q_PROPERTY(QDateTime birthdate READ birthdate WRITE set_birthdate NOTIFY birthdateChanged)

  friend class AuthorPtr;

public:
  Author();
  Author(const Author & other);
  Author(const QJsonObject & json_object); // JSON deserializer
  Author(const QVariantHash & variant_hash);
  Author(const QVariantList & variants);
  Author(const QSqlRecord & record); // SQL deserializer
  Author(const QSqlQuery & query, int offset = 0); // SQL deserializer
  ~Author();

  Author & operator=(const Author & other);

  bool operator==(const Author & other);

  // Getter/Setter

  int id() const { return m_id; }
  void set_id(int value);

  const QString & name() const { return m_name; }
  void set_name(const QString & value);

  const QDateTime & birthdate() const { return m_birthdate; }
  void set_birthdate(const QDateTime & value);

  void set_insert_id(int id) { set_id(id); }

  // JSON Serializer
  QJsonObject to_json(bool only_changed = false) const;

  // Generic Variant Serializer
  QVariantHash to_variant_hash(bool only_changed = false) const;
  QVariantList to_variant_list() const;

  // SQL Serializer
  QVariantHash to_variant_hash_sql(bool only_changed = false, bool duplicate = false) const;
  QVariantList to_variant_list_sql(bool duplicate = false) const;

  // Query for update
  bool is_id_modified() const { return bit_status(Schema::Fields::ID); }
  bool is_name_modified() const { return bit_status(Schema::Fields::NAME); }
  bool is_birthdate_modified() const { return bit_status(Schema::Fields::BIRTHDATE); }

  // Field accessor by position
  QVariant field(int position) const;
  void set_field(int position, const QVariant & value);

  void load_relations();
  QcRowList<Blog> & blogs() { return m_blogs; }
  

signals:
  void idChanged();
  void nameChanged();
  void birthdateChanged();

private:
  int m_id;
  QString m_name;
  QDateTime m_birthdate;
  QcRowList<Blog> m_blogs;
  
};

class AuthorPtr
{
public:
  typedef Author Class;

public:
  AuthorPtr() : m_ptr() {}
  AuthorPtr(const Class & other) : m_ptr(new Class(other)) {}
  AuthorPtr(const QJsonObject & json_object) : m_ptr(new Class(json_object)) {}
  AuthorPtr(const QVariantHash & variant_hash) : m_ptr(new Class(variant_hash)) {}
  AuthorPtr(const QVariantList & variants) : m_ptr(new Class(variants)) {}
  AuthorPtr(const QSqlRecord & record) : m_ptr(new Class(record)) {}
  AuthorPtr(const QSqlQuery & query, int offset = 0) : m_ptr(new Class(query, offset)) {}
  ~AuthorPtr() {}

  QSharedPointer<Class> & ptr() { return m_ptr; }

  Class & operator*() const { return *m_ptr; }
  Class * operator->() const { return m_ptr.data(); }

private:
  QSharedPointer<Class> m_ptr;
};

QDataStream & operator<<(QDataStream & out, const Author & obj);
QDataStream & operator>>(QDataStream & in, Author & obj);
// qRegisterMetaTypeStreamOperators<Author>("Author");

#ifndef QT_NO_DEBUG_STREAM
QDebug operator<<(QDebug debug, const Author & obj);
#endif

/**************************************************************************************************/

class Category;

class CategorySchema : public QcSchema
{
public:
  enum Fields {
    ID,
    NAME,
    DESCRIPTION
  };
  static const int NUMBER_OF_FIELDS = 3;

public:
  static CategorySchema & instance()
  {
    static CategorySchema m_instance;
    return m_instance;
  }

  // delete copy and move constructors and assign operators
  CategorySchema(const CategorySchema &) = delete;
  CategorySchema(CategorySchema &&) = delete;
  CategorySchema & operator=(const CategorySchema &) = delete;
  CategorySchema & operator=(CategorySchema &&) = delete;

protected:
  CategorySchema();
  ~CategorySchema();
};

/**************************************************************************************************/



class CategoryPtr;



class Category : public QObject, public QcRow<CategorySchema>
{
  Q_OBJECT
  Q_PROPERTY(int id READ id WRITE set_id NOTIFY idChanged)
  Q_PROPERTY(QString name READ name WRITE set_name NOTIFY nameChanged)
  Q_PROPERTY(QString description READ description WRITE set_description NOTIFY descriptionChanged)

  friend class CategoryPtr;

public:
  Category();
  Category(const Category & other);
  Category(const QJsonObject & json_object); // JSON deserializer
  Category(const QVariantHash & variant_hash);
  Category(const QVariantList & variants);
  Category(const QSqlRecord & record); // SQL deserializer
  Category(const QSqlQuery & query, int offset = 0); // SQL deserializer
  ~Category();

  Category & operator=(const Category & other);

  bool operator==(const Category & other);

  // Getter/Setter

  int id() const { return m_id; }
  void set_id(int value);

  const QString & name() const { return m_name; }
  void set_name(const QString & value);

  const QString & description() const { return m_description; }
  void set_description(const QString & value);

  void set_insert_id(int id) { set_id(id); }

  // JSON Serializer
  QJsonObject to_json(bool only_changed = false) const;

  // Generic Variant Serializer
  QVariantHash to_variant_hash(bool only_changed = false) const;
  QVariantList to_variant_list() const;

  // SQL Serializer
  QVariantHash to_variant_hash_sql(bool only_changed = false, bool duplicate = false) const;
  QVariantList to_variant_list_sql(bool duplicate = false) const;

  // Query for update
  bool is_id_modified() const { return bit_status(Schema::Fields::ID); }
  bool is_name_modified() const { return bit_status(Schema::Fields::NAME); }
  bool is_description_modified() const { return bit_status(Schema::Fields::DESCRIPTION); }

  // Field accessor by position
  QVariant field(int position) const;
  void set_field(int position, const QVariant & value);

signals:
  void idChanged();
  void nameChanged();
  void descriptionChanged();

private:
  int m_id;
  QString m_name;
  QString m_description;
};

class CategoryPtr
{
public:
  typedef Category Class;

public:
  CategoryPtr() : m_ptr() {}
  CategoryPtr(const Class & other) : m_ptr(new Class(other)) {}
  CategoryPtr(const QJsonObject & json_object) : m_ptr(new Class(json_object)) {}
  CategoryPtr(const QVariantHash & variant_hash) : m_ptr(new Class(variant_hash)) {}
  CategoryPtr(const QVariantList & variants) : m_ptr(new Class(variants)) {}
  CategoryPtr(const QSqlRecord & record) : m_ptr(new Class(record)) {}
  CategoryPtr(const QSqlQuery & query, int offset = 0) : m_ptr(new Class(query, offset)) {}
  ~CategoryPtr() {}

  QSharedPointer<Class> & ptr() { return m_ptr; }

  Class & operator*() const { return *m_ptr; }
  Class * operator->() const { return m_ptr.data(); }

private:
  QSharedPointer<Class> m_ptr;
};

QDataStream & operator<<(QDataStream & out, const Category & obj);
QDataStream & operator>>(QDataStream & in, Category & obj);
// qRegisterMetaTypeStreamOperators<Category>("Category");

#ifndef QT_NO_DEBUG_STREAM
QDebug operator<<(QDebug debug, const Category & obj);
#endif

/**************************************************************************************************/

class Blog;

class BlogSchema : public QcSchema
{
public:
  enum Fields {
    ID,
    TEXT,
    DATE,
    AUTHOR_ID
  };
  static const int NUMBER_OF_FIELDS = 4;

public:
  static BlogSchema & instance()
  {
    static BlogSchema m_instance;
    return m_instance;
  }

  // delete copy and move constructors and assign operators
  BlogSchema(const BlogSchema &) = delete;
  BlogSchema(BlogSchema &&) = delete;
  BlogSchema & operator=(const BlogSchema &) = delete;
  BlogSchema & operator=(BlogSchema &&) = delete;

protected:
  BlogSchema();
  ~BlogSchema();
};

/**************************************************************************************************/



class BlogPtr;





class Blog : public QObject, public QcRow<BlogSchema>
{
  Q_OBJECT
  Q_PROPERTY(int id READ id WRITE set_id NOTIFY idChanged)
  Q_PROPERTY(QString text READ text WRITE set_text NOTIFY textChanged)
  Q_PROPERTY(QDateTime date READ date WRITE set_date NOTIFY dateChanged)
  Q_PROPERTY(int author_id READ author_id WRITE set_author_id NOTIFY author_idChanged)

  friend class BlogPtr;

public:
  Blog();
  Blog(const Blog & other);
  Blog(const QJsonObject & json_object); // JSON deserializer
  Blog(const QVariantHash & variant_hash);
  Blog(const QVariantList & variants);
  Blog(const QSqlRecord & record); // SQL deserializer
  Blog(const QSqlQuery & query, int offset = 0); // SQL deserializer
  ~Blog();

  Blog & operator=(const Blog & other);

  bool operator==(const Blog & other);

  // Getter/Setter

  int id() const { return m_id; }
  void set_id(int value);

  const QString & text() const { return m_text; }
  void set_text(const QString & value);

  const QDateTime & date() const { return m_date; }
  void set_date(const QDateTime & value);

  int author_id() const { return m_author_id; }
  void set_author_id(int value);

  void set_insert_id(int id) { set_id(id); }

  // JSON Serializer
  QJsonObject to_json(bool only_changed = false) const;

  // Generic Variant Serializer
  QVariantHash to_variant_hash(bool only_changed = false) const;
  QVariantList to_variant_list() const;

  // SQL Serializer
  QVariantHash to_variant_hash_sql(bool only_changed = false, bool duplicate = false) const;
  QVariantList to_variant_list_sql(bool duplicate = false) const;

  // Query for update
  bool is_id_modified() const { return bit_status(Schema::Fields::ID); }
  bool is_text_modified() const { return bit_status(Schema::Fields::TEXT); }
  bool is_date_modified() const { return bit_status(Schema::Fields::DATE); }
  bool is_author_id_modified() const { return bit_status(Schema::Fields::AUTHOR_ID); }

  // Field accessor by position
  QVariant field(int position) const;
  void set_field(int position, const QVariant & value);

  void load_relations();
  QSharedPointer<Author> author();
  void set_author(QSharedPointer<Author> & value);
  

signals:
  void idChanged();
  void textChanged();
  void dateChanged();
  void author_idChanged();

private:
  int m_id;
  QString m_text;
  QDateTime m_date;
  int m_author_id;
  QSharedPointer<Author> m_author = nullptr;
  
};

class BlogPtr
{
public:
  typedef Blog Class;

public:
  BlogPtr() : m_ptr() {}
  BlogPtr(const Class & other) : m_ptr(new Class(other)) {}
  BlogPtr(const QJsonObject & json_object) : m_ptr(new Class(json_object)) {}
  BlogPtr(const QVariantHash & variant_hash) : m_ptr(new Class(variant_hash)) {}
  BlogPtr(const QVariantList & variants) : m_ptr(new Class(variants)) {}
  BlogPtr(const QSqlRecord & record) : m_ptr(new Class(record)) {}
  BlogPtr(const QSqlQuery & query, int offset = 0) : m_ptr(new Class(query, offset)) {}
  ~BlogPtr() {}

  QSharedPointer<Class> & ptr() { return m_ptr; }

  Class & operator*() const { return *m_ptr; }
  Class * operator->() const { return m_ptr.data(); }
  void set_author(AuthorPtr & value);


private:
  QSharedPointer<Class> m_ptr;
};

QDataStream & operator<<(QDataStream & out, const Blog & obj);
QDataStream & operator>>(QDataStream & in, Blog & obj);
// qRegisterMetaTypeStreamOperators<Blog>("Blog");

#ifndef QT_NO_DEBUG_STREAM
QDebug operator<<(QDebug debug, const Blog & obj);
#endif

/**************************************************************************************************/

class Comment;

class CommentSchema : public QcSchema
{
public:
  enum Fields {
    ID,
    TEXT,
    DATE,
    BLOG_ID
  };
  static const int NUMBER_OF_FIELDS = 4;

public:
  static CommentSchema & instance()
  {
    static CommentSchema m_instance;
    return m_instance;
  }

  // delete copy and move constructors and assign operators
  CommentSchema(const CommentSchema &) = delete;
  CommentSchema(CommentSchema &&) = delete;
  CommentSchema & operator=(const CommentSchema &) = delete;
  CommentSchema & operator=(CommentSchema &&) = delete;

protected:
  CommentSchema();
  ~CommentSchema();
};

/**************************************************************************************************/



class CommentPtr;



class Comment : public QObject, public QcRow<CommentSchema>
{
  Q_OBJECT
  Q_PROPERTY(int id READ id WRITE set_id NOTIFY idChanged)
  Q_PROPERTY(QString text READ text WRITE set_text NOTIFY textChanged)
  Q_PROPERTY(QDateTime date READ date WRITE set_date NOTIFY dateChanged)
  Q_PROPERTY(int blog_id READ blog_id WRITE set_blog_id NOTIFY blog_idChanged)

  friend class CommentPtr;

public:
  Comment();
  Comment(const Comment & other);
  Comment(const QJsonObject & json_object); // JSON deserializer
  Comment(const QVariantHash & variant_hash);
  Comment(const QVariantList & variants);
  Comment(const QSqlRecord & record); // SQL deserializer
  Comment(const QSqlQuery & query, int offset = 0); // SQL deserializer
  ~Comment();

  Comment & operator=(const Comment & other);

  bool operator==(const Comment & other);

  // Getter/Setter

  int id() const { return m_id; }
  void set_id(int value);

  const QString & text() const { return m_text; }
  void set_text(const QString & value);

  const QDateTime & date() const { return m_date; }
  void set_date(const QDateTime & value);

  int blog_id() const { return m_blog_id; }
  void set_blog_id(int value);

  void set_insert_id(int id) { set_id(id); }

  // JSON Serializer
  QJsonObject to_json(bool only_changed = false) const;

  // Generic Variant Serializer
  QVariantHash to_variant_hash(bool only_changed = false) const;
  QVariantList to_variant_list() const;

  // SQL Serializer
  QVariantHash to_variant_hash_sql(bool only_changed = false, bool duplicate = false) const;
  QVariantList to_variant_list_sql(bool duplicate = false) const;

  // Query for update
  bool is_id_modified() const { return bit_status(Schema::Fields::ID); }
  bool is_text_modified() const { return bit_status(Schema::Fields::TEXT); }
  bool is_date_modified() const { return bit_status(Schema::Fields::DATE); }
  bool is_blog_id_modified() const { return bit_status(Schema::Fields::BLOG_ID); }

  // Field accessor by position
  QVariant field(int position) const;
  void set_field(int position, const QVariant & value);

signals:
  void idChanged();
  void textChanged();
  void dateChanged();
  void blog_idChanged();

private:
  int m_id;
  QString m_text;
  QDateTime m_date;
  int m_blog_id;
};

class CommentPtr
{
public:
  typedef Comment Class;

public:
  CommentPtr() : m_ptr() {}
  CommentPtr(const Class & other) : m_ptr(new Class(other)) {}
  CommentPtr(const QJsonObject & json_object) : m_ptr(new Class(json_object)) {}
  CommentPtr(const QVariantHash & variant_hash) : m_ptr(new Class(variant_hash)) {}
  CommentPtr(const QVariantList & variants) : m_ptr(new Class(variants)) {}
  CommentPtr(const QSqlRecord & record) : m_ptr(new Class(record)) {}
  CommentPtr(const QSqlQuery & query, int offset = 0) : m_ptr(new Class(query, offset)) {}
  ~CommentPtr() {}

  QSharedPointer<Class> & ptr() { return m_ptr; }

  Class & operator*() const { return *m_ptr; }
  Class * operator->() const { return m_ptr.data(); }

private:
  QSharedPointer<Class> m_ptr;
};

QDataStream & operator<<(QDataStream & out, const Comment & obj);
QDataStream & operator>>(QDataStream & in, Comment & obj);
// qRegisterMetaTypeStreamOperators<Comment>("Comment");

#ifndef QT_NO_DEBUG_STREAM
QDebug operator<<(QDebug debug, const Comment & obj);
#endif

/**************************************************************************************************/


class BlogApplicationSchema : public QcDatabaseSchema
{
public:
  BlogApplicationSchema(QcDatabase & database);
  BlogApplicationSchema(const BlogApplicationSchema & other) = delete;
  ~BlogApplicationSchema();

  BlogApplicationSchema & operator=(const BlogApplicationSchema & other) = delete;

  QcDatabaseTable & authors() { return *m_authors; }
  QcDatabaseTable & categories() { return *m_categories; }
  QcDatabaseTable & blogs() { return *m_blogs; }
  QcDatabaseTable & comments() { return *m_comments; }

private:
  QcDatabaseTable * m_authors;
  QcDatabaseTable * m_categories;
  QcDatabaseTable * m_blogs;
  QcDatabaseTable * m_comments;
};

/**************************************************************************************************/

#endif /* __BLOG_H__ */

/***************************************************************************************************
 *
 * End
 *
 **************************************************************************************************/
