// This file was automatically generated by SqlOrm
/***************************************************************************************************
 *
 * $QTCARTO_BEGIN_LICENSE:GPL3$
 *
 * Copyright (C) 2016 Fabrice Salvaire
 * Contact: http://www.fabrice-salvaire.fr
 *
 * This file is part of the QtCarto library.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * $QTCARTO_END_LICENSE$
 *
 **************************************************************************************************/

/**************************************************************************************************/

#include "document.h"

/**************************************************************************************************/

// QC_BEGIN_NAMESPACE
DocumentSchema::DocumentSchema()
: QcSchema(QLatin1String("Document"))
{
  add_field(QcSchemaField(QLatin1String("id"),
                          QLatin1String("int"),
                          QLatin1String("integer")));
  add_field(QcSchemaField(QLatin1String("name"),
                          QLatin1String("QString"),
                          QLatin1String("text")));
  add_field(QcSchemaField(QLatin1String("author"),
                          QLatin1String("QString"),
                          QLatin1String("text")));
  add_field(QcSchemaField(QLatin1String("version"),
                          QLatin1String("int"),
                          QLatin1String("integer")));
  add_field(QcSchemaField(QLatin1String("date"),
                          QLatin1String("QDateTime"),
                          QLatin1String("text")));
  add_field(QcSchemaField(QLatin1String("description"),
                          QLatin1String("QString"),
                          QLatin1String("text")));
  add_field(QcSchemaField(QLatin1String("url"),
                          QLatin1String("QUrl"),
                          QLatin1String("text")));
  add_field(QcSchemaField(QLatin1String("size"),
                          QLatin1String("int"),
                          QLatin1String("integer")));
}

DocumentSchema::~DocumentSchema()
{}

/**************************************************************************************************/

Document::Document()
  : m_bits(8),
    m_id(),
    m_name(),
    m_author(),
    m_version(),
    m_date(),
    m_description(),
    m_url(),
    m_size()
{}

Document::Document(const Document & other)
  : m_bits(other.m_bits),
    m_id(other.m_id),
    m_name(other.m_name),
    m_author(other.m_author),
    m_version(other.m_version),
    m_date(other.m_date),
    m_description(other.m_description),
    m_url(other.m_url),
    m_size(other.m_size)
{}

Document::Document(const QJsonObject & json_object)
 : Document()
{
   m_id = json_object[QLatin1String("id")].toInt();
   m_name = json_object[QLatin1String("name")].toString();
   m_author = json_object[QLatin1String("author")].toString();
   m_version = json_object[QLatin1String("version")].toInt();
   m_date = json_object[QLatin1String("date")].toVariant().toDateTime();
   m_description = json_object[QLatin1String("description")].toString();
   m_url = json_object[QLatin1String("url")].toString();
   m_size = json_object[QLatin1String("size")].toInt();
}

Document::Document(const QVariantMap & variant_map)
 : Document()
{
   m_id = variant_map[QLatin1String("id")].toInt();
   m_name = variant_map[QLatin1String("name")].toString();
   m_author = variant_map[QLatin1String("author")].toString();
   m_version = variant_map[QLatin1String("version")].toInt();
   m_date = variant_map[QLatin1String("date")].toDateTime();
   m_description = variant_map[QLatin1String("description")].toString();
   m_url = variant_map[QLatin1String("url")].toUrl();
   m_size = variant_map[QLatin1String("size")].toInt();
}

Document::~Document()
{}

Document &
Document::operator=(const Document & other)
{
  if (this != &other) {
    m_bits = other.m_bits;
    m_id = other.m_id;
    m_name = other.m_name;
    m_author = other.m_author;
    m_version = other.m_version;
    m_date = other.m_date;
    m_description = other.m_description;
    m_url = other.m_url;
    m_size = other.m_size;
  }

  return *this;
}

bool
Document::operator==(const Document & other)
{
  if (m_bits != other.m_bits)
    return false;
  if (m_id != other.m_id)
    return false;
  if (m_name != other.m_name)
    return false;
  if (m_author != other.m_author)
    return false;
  if (m_version != other.m_version)
    return false;
  if (m_date != other.m_date)
    return false;
  if (m_description != other.m_description)
    return false;
  if (m_url != other.m_url)
    return false;
  if (m_size != other.m_size)
    return false;

  return true;
}

void
Document::set_id(int value)
{
  if (m_id != value) {
    m_id = value;
    m_bits.setBit(DocumentSchema::FieldPosition::ID);
    emit idChanged();
  }
}

void
Document::set_name(const QString & value)
{
  if (m_name != value) {
    m_name = value;
    m_bits.setBit(DocumentSchema::FieldPosition::NAME);
    emit nameChanged();
  }
}

void
Document::set_author(const QString & value)
{
  if (m_author != value) {
    m_author = value;
    m_bits.setBit(DocumentSchema::FieldPosition::AUTHOR);
    emit authorChanged();
  }
}

void
Document::set_version(int value)
{
  if (m_version != value) {
    m_version = value;
    m_bits.setBit(DocumentSchema::FieldPosition::VERSION);
    emit versionChanged();
  }
}

void
Document::set_date(const QDateTime & value)
{
  if (m_date != value) {
    m_date = value;
    m_bits.setBit(DocumentSchema::FieldPosition::DATE);
    emit dateChanged();
  }
}

void
Document::set_description(const QString & value)
{
  if (m_description != value) {
    m_description = value;
    m_bits.setBit(DocumentSchema::FieldPosition::DESCRIPTION);
    emit descriptionChanged();
  }
}

void
Document::set_url(const QUrl & value)
{
  if (m_url != value) {
    m_url = value;
    m_bits.setBit(DocumentSchema::FieldPosition::URL);
    emit urlChanged();
  }
}

void
Document::set_size(int value)
{
  if (m_size != value) {
    m_size = value;
    m_bits.setBit(DocumentSchema::FieldPosition::SIZE);
    emit sizeChanged();
  }
}

QJsonObject
Document::to_json(bool only_changed) const
{
  QJsonObject json_object;

 if (only_changed) {
    if (is_id_modified())
      json_object.insert(QLatin1String("id"), QJsonValue(m_id));
    if (is_name_modified())
      json_object.insert(QLatin1String("name"), QJsonValue(m_name));
    if (is_author_modified())
      json_object.insert(QLatin1String("author"), QJsonValue(m_author));
    if (is_version_modified())
      json_object.insert(QLatin1String("version"), QJsonValue(m_version));
    if (is_date_modified())
      json_object.insert(QLatin1String("date"), QJsonValue(m_date.toString(Qt::ISODate)));
    if (is_description_modified())
      json_object.insert(QLatin1String("description"), QJsonValue(m_description));
    if (is_url_modified())
      json_object.insert(QLatin1String("url"), QJsonValue(m_url.toString()));
    if (is_size_modified())
      json_object.insert(QLatin1String("size"), QJsonValue(m_size));
  } else {
    json_object.insert(QLatin1String("id"), QJsonValue(m_id));
    json_object.insert(QLatin1String("name"), QJsonValue(m_name));
    json_object.insert(QLatin1String("author"), QJsonValue(m_author));
    json_object.insert(QLatin1String("version"), QJsonValue(m_version));
    json_object.insert(QLatin1String("date"), QJsonValue(m_date.toString(Qt::ISODate)));
    json_object.insert(QLatin1String("description"), QJsonValue(m_description));
    json_object.insert(QLatin1String("url"), QJsonValue(m_url.toString()));
    json_object.insert(QLatin1String("size"), QJsonValue(m_size));
  }

  return json_object;
}

QVariantMap
Document::to_variant_map(bool only_changed) const
{
  QVariantMap variant_map;

 if (only_changed) {
    if (is_id_modified())
      variant_map[QLatin1String("id")] = m_id;
    if (is_name_modified())
      variant_map[QLatin1String("name")] = m_name;
    if (is_author_modified())
      variant_map[QLatin1String("author")] = m_author;
    if (is_version_modified())
      variant_map[QLatin1String("version")] = m_version;
    if (is_date_modified())
      variant_map[QLatin1String("date")] = m_date;
    if (is_description_modified())
      variant_map[QLatin1String("description")] = m_description;
    if (is_url_modified())
      variant_map[QLatin1String("url")] = m_url;
    if (is_size_modified())
      variant_map[QLatin1String("size")] = m_size;
  } else {
    variant_map[QLatin1String("id")] = m_id;
    variant_map[QLatin1String("name")] = m_name;
    variant_map[QLatin1String("author")] = m_author;
    variant_map[QLatin1String("version")] = m_version;
    variant_map[QLatin1String("date")] = m_date;
    variant_map[QLatin1String("description")] = m_description;
    variant_map[QLatin1String("url")] = m_url;
    variant_map[QLatin1String("size")] = m_size;
  }

  return variant_map;
}

QDataStream &
operator<<(QDataStream & out, const Document & obj)
{
  out << obj.id();
  out << obj.name();
  out << obj.author();
  out << obj.version();
  out << obj.date();
  out << obj.description();
  out << obj.url();
  out << obj.size();

  return out;
}

QDataStream &
operator>>(QDataStream & in, Document & obj)
{
  QDateTime _QDateTime;
  int _int;
  QUrl _QUrl;
  QString _QString;

  in >> _int;
  obj.set_id(_int);
  in >> _QString;
  obj.set_name(_QString);
  in >> _QString;
  obj.set_author(_QString);
  in >> _int;
  obj.set_version(_int);
  in >> _QDateTime;
  obj.set_date(_QDateTime);
  in >> _QString;
  obj.set_description(_QString);
  in >> _QUrl;
  obj.set_url(_QUrl);
  in >> _int;
  obj.set_size(_int);

  return in;
}

#ifndef QT_NO_DEBUG_STREAM
QDebug
operator<<(QDebug debug, const Document & obj)
{
  QDebugStateSaver saver(debug); // Fixme: ???

  debug.nospace() << QLatin1Literal("Document(");
  debug << obj.id();
  debug << QLatin1Literal(", ");
  debug << obj.name();
  debug << QLatin1Literal(", ");
  debug << obj.author();
  debug << QLatin1Literal(", ");
  debug << obj.version();
  debug << QLatin1Literal(", ");
  debug << obj.date();
  debug << QLatin1Literal(", ");
  debug << obj.description();
  debug << QLatin1Literal(", ");
  debug << obj.url();
  debug << QLatin1Literal(", ");
  debug << obj.size();
  debug << ')';

  return debug;
}
#endif

// QC_END_NAMESPACE

/***************************************************************************************************
 *
 * End
 *
 **************************************************************************************************/
