#! /bin/bash

svg_path="../icon-resources/svg"
png_path="${svg_path}/png"

mkdir -p ${png_path}

for i in ${svg_path}/*.svg; do
  n=${i##*/}
  n=${n%%.svg}
  n="$n-black"

  if [[ $i -nt ${png_path}/$n.png ]]; then
    echo Generate $n

    options="--export-area-page --export-background=white --export-background-opacity=0"
    inkscape --export-png=${png_path}/$n.png ${options} --export-width=24 --export-height=24 $i
    inkscape --export-png=${png_path}/$n@3x.png ${options} --export-width=72 --export-height=72 $i

    ln -sf ${png_path}/$n.png $n.png
    ln -sf ${png_path}/$n@3x.png $n@3x.png
  fi
done
