#! /bin/bash

pushd third-party

pushd cmark
git clone https://github.com/github/cmark cmark.git

# git clone https://github.com/OSGeo/proj.4.git
# git clone https://github.com/libspatialindex/libspatialindex.git
