#! /bin/bash

svg_path="../icon-ressources/svg"
png_path="${svg_path}/png"

mkdir -p ${png_path}

for i in ${svg_path}/*.svg; do
  n=${i##*/}
  n=${n%%.svg}
  echo $n
  n="$n-black"

  convert $i -resize 24x24 -transparent white ${png_path}/$n.png
  convert $i -resize 72x72 -transparent white ${png_path}/$n@3x.png

  ln -sf ${png_path}/$n.png $n.png
  ln -sf ${png_path}/$n@3x.png $n@3x.png
done
