#! /usr/bin/bash

#STYLE=Default
STYLE=Material

QT_VERSION=5.10.0

QT_QUICK_CONTROLS_STYLE=$STYLE \
 /opt/Qt/${QT_VERSION}/gcc_64/bin/qmlscene \
 -I /home/fabrice/home/developpement/qtcarto-application/alpine-toolkit/ressources/qml \
 qml-test.qml

# /opt/Qt/5.10.0/gcc_64/bin/qmlscene qml-test.qml
