#! /bin/bash

####################################################################################################
#
# Build Apline Toolkit on X86
#
####################################################################################################

####################################################################################################

source_path=`realpath $0`
source_path=`dirname ${source_path}`
source_path=`dirname ${source_path}`
build_path=${source_path}/build-cmake

QT_VERSION=5.13.0

export CFLAGS="-g -O0"
export CXXFLAGS="${CFLAGS}"
BUILD_TYPE=DEBUG

# https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html
# set_gcc_optimisation
# export CFLAGS="-O3 -march=broadwell -mtune=broadwell -flto"
# export CXXFLAGS="${CFLAGS}"
# BUILD_TYPE=RELEASE

####################################################################################################

source $HOME/.bashrc

append_to_path_if_not /opt/Qt/${QT_VERSION}/gcc_64/bin/
append_to_ld_library_path_if_not /opt/Qt/${QT_VERSION}/gcc_64/lib/

if ! [ -e ${build_path} ]; then
  mkdir ${build_path}
fi
pushd ${build_path}

rm -f CMakeCache.txt
rm -f compile_commands.json
if [ -e Makefile ]; then
  make clean
fi

# /etc/security/limits.d/00-user.conf
# -DSANITIZE=ON

cmake \
  -D CMAKE_BUILD_TYPE:STRING=={BUILD_TYPE} \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DSANITIZE=OFF \
  -DINSTRUMENT_FUNTIONS=OFF \
  ${source_path}

make -j4

if [ -e run-asan ]; then
  ln -sf ../build-scripts/run-asan.sh
fi

# source run-asan.sh
